language: python

python:
- 3.5

env:
- DJANGO=1.11.6

install:
- pip install -r requirements.txt
- pip install codeclimate-test-reporter
- pip install -q Django==$DJANGO

script:
- coverage run --source=habitica_slack manage.py test # create test coverage report

after_script:
- codeclimate-test-reporter --file .coverage # send test coverage report to code climate

after_success: 
- coverage report